version: "3.8"

services:
  url-shortener:
    build: .
    image: cch1006/url-shortener:latest
    ports:
      - "8000:8000"
    volumes:
      - url_data:/data
    restart: always

volumes:
  url_data:
    driver: local
